### ISSUE TITLE
Problem with responsiveness on mobile phones

### ISSUE THREAD

**Issue by SerekKiri** [xXmilanek/xxmilanek.github.io#1]

**Comment by xXmilanek** [comment]
Yeah, i've  noticed. Im stil working on this

**Comment by xxczaki** [comment]
> inb4, I'm helping @xXmilanek making his first steps on Github, do not punish him if the code on this site is bad ;)

I think media queries are the best option here. However, I'm not going to do this, because I have other projects to maintain :cry: I can help with JS, CSS is not my piece of cake. Maybe someone doing Hacktoberfest challenge will take this task.

**Comment by clsoar** [comment]
I can work on this issue if you would like.

**Comment by xxczaki** [comment]
@clsoar that would be great!
