### ISSUE TITLE
Use Font Awesome 5 instead of fontello

### ISSUE THREAD

**Issue by xxczaki** [xXmilanek/xxmilanek.github.io#5]
We should use fa5 instead of fontello. Some CSS changes might need to be done, because of the different styling rules. I can take care of that, but maybe someone doing the Hacktoberfest challenge will take this quicker :unicorn:

**Comment by Thilagavathi1** [comment]
@xxczaki Submitted PR please check it.

**Comment by xXmilanek** [comment]
Imo i doesnt look how it should be. But still waiting for @xxczaki  decision.

**Comment by iamj4james** [comment]
@xxczaki  I would like to look at this project

**Comment by xxczaki** [comment]
closed because I already implemented it. @iamj4james You can try to make this site more mobile friendly or clean up css & html code ;)
